---
version: "2"

services:
  tor-socks-proxy:
    container_name: tor-socks-proxy
    image: registry-1.docker.io/jackysedi/tor-socks-proxy:latest
    ports:
      - "127.0.0.1:9150:9150"
    restart: unless-stopped
    
  test:
    container_name: test
    image: test:latest
