---
version: "2"

services:
  tor-socks-proxy:
    container_name: tor-socks-proxy
    hostname: tor-socks-proxy
    image: registry-1.docker.io/jackysedi/tor-socks-proxy:latest
    ports:
      - "127.0.0.1:XXXX:9150"
    networks:
      - proxy
    restart: unless-stopped
    
  test:
    container_name: test
    hostname: test
    image: test:latest
    environment:
     - PORT=XXXX
    networks:
      - test
     
     
networks:
  proxy:
    driver: bridge
  test:
    driver: bridge
     
